language: go
env:
- GO111MODULE=on
go:
- "1.8"
go_import_path: github.com/pierback/bchain-qlearning
git:
  depth: 1
# install: true
notifications:
  email: false
before_script:
- rvm install 2.2.5
- go get -t -v ./...
script:
- go test -v -race ./...
deploy:
  provider: releases
  api_key:
    secure: XuZXSALVIaFQKqa221sjlsCEOrMHIpFH26QMC8xrXwbi2Dl2m1A4fXgOl1NBGY766j64kACKuo7i74nBjhroIbw2rex/9KJp6vwLh8n/RP0tFCMMhYApu5wkvKSeLuKf51oMO53cfEibk4riN+L3M3T9sZsRD38w81f1OmLl5THA2Rw7wi+E6knW8xG1+c9ttst6rOY5qzXcdGnWUP2rt4zP+tI8VMv+PphRDnHHL22sit92R3J3nUIFxjuNgMmnoMn9+314qglKvxWYjdEhEczqgfZz3iyzAlLiwcLc4qTilsL0+hXSimgihP1AlTlya+3hvDXNPmbfTMJ8/oJsoy0XOSvFgASipVtLpjc0sMzikgjOCiVQ8OdT4bNA2AcypGXByIeu9MRp3OM3gz8uxjyJC2gVUOTdzR56yUZZF3crVUCaY5/7HOonvdOoBxWjC3Brjg2derHHSgDMCk39f4KrvujyfvJkfRWVzdHEkIkmgnp6NnV4m3xg4gmEUeblEidd44yZeDAeDq+wOguNC2Dhippx4UaLvvi7RIXOMNYp92q+g6GEAKFeV+6COl2dgQ0qwA+KqwX4cPhM1O67cfER/xBchiDqn+8KJJOBusKMi+5whVS9dUBoAE782Q2gX3GqhfaRNv0QhvvSNr5cpXNDjoWbueuhKD0QCe7Jxhc=
  file: ''
  on:
    repo: pierback/bchain-qlearning
    branch: feature/restructure-project
