language: go
go:
  - 1.10.x
  - master
go_import_path: github.com/pierback/bchain-qlearning
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -v -race ./...
