language: go
env:
- GO111MODULE=on
go:
 - tip
go_import_path: github.com/pierback/bchain-qlearning
git:
  depth: 1
install: true
notifications:
  email: false
before_script:
- go get -t -v ./...
script:
- go test -v -race ./...
