// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  learning

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( QLearning ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* QLearning ) UnmarshalJSON([]byte) error { return nil }
func ( QLearning ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* QLearning ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_QLearning *QLearning
